### ISSUE TITLE
generate方法在哪？

### ISSUE THREAD

**Issue by renxingkai** [renmada/t5-pegasus-pytorch#11]
想查看
`output = model.generate(ids,
                            decoder_start_token_id=tokenizer.cls_token_id,
                            eos_token_id=tokenizer.sep_token_id,
                            max_length=30).numpy()[0]`
中的generate方法内部实现，但是MT5ForConditionalGeneration及其继承的父类T5ForConditionalGeneration、T5PreTrainedModel、PreTrainedModel等源码中均未找到，想请教下具体的实现在哪？

**Comment by renmada** [comment]
![image](https://user-images.githubusercontent.com/43545086/122049764-5c1d6f00-ce15-11eb-99cd-3ead4a6f2c3f.png)
在这里

**Comment by renxingkai** [comment]
> ![image](https://user-images.githubusercontent.com/43545086/122049764-5c1d6f00-ce15-11eb-99cd-3ead4a6f2c3f.png)
> 在这里

OK，谢谢谢谢
