### ISSUE TITLE
追一科技的chinese_t5_pegasus_base转torch， convert.py报错：Can't set hidden_size with value 768 for MT5Config

### ISSUE THREAD

**Issue by mode007** [renmada/t5-pegasus-pytorch#12]
你好，运行运行convert.py的时候，把追一科技的chinese_t5_pegasus_base转成torch时候报错，Can't set hidden_size with value 768 for MT5Config，请问是什么原因呢？

**Comment by renmada** [comment]
信息太少了，没法判断

**Comment by mode007** [comment]
就是在执行convert.py时，config = MT5Config.from_pretrained('/chinese_t5_pegasus_base/config.json') 这句报错，追一科技的chinese_t5_pegasus_base的config.json与transformers的MT5Config.from_pretrained对应不上，
报错信息是：
Can't set hidden_size with value 768 for MT5Config {
  "decoder_start_token_id": 0,
  "eos_token_id": 1,
  "hidden_act": [
    "gelu",
    "linear"
  ],
  "hidden_dropout_prob": 0.1,
  "is_encoder_decoder": true,
  "model_type": "mt5",
  "pad_token_id": 0,
  "tie_word_embeddings": false,
  "tokenizer_class": "T5Tokenizer",
  "transformers_version": "4.5.1"
}
AttributeError: can't set attribute
想问一下你当时转的时候有这个错误吗？

**Comment by renmada** [comment]
config不是原版的config
参考这个格式的config
https://huggingface.co/imxly/t5-pegasus/blob/main/config.json

**Comment by mode007** [comment]
感谢解答，再请问一个问题，我用追一科技的代码train.py重新预训练了t5,最后保存的模型是keras保存的.weights文件,需要转成ckpt才能用这里的convert.py,请问你预训练的时候遇到过这个问题吗，是怎么解决的呢？

**Comment by renmada** [comment]
我没有做预训练，只是转成pytorch以后来finetune。
重新训练的时候应可以用tf.keras来训练，可以直接save ckpt

**Comment by mode007** [comment]
好的，谢谢解答。

**Comment by jiangliqin** [comment]
> 感谢解答，再请问一个问题，我用追一科技的代码train.py重新预训练了t5,最后保存的模型是keras保存的.weights文件,需要转成ckpt才能用这里的convert.py,请问你预训练的时候遇到过这个问题吗，是怎么解决的呢？

请问你是怎么将.weights文件转成ckpt?

**Comment by Mrxkai** [comment]
> Author



> 感谢解答，再请问一个问题，我用追一科技的代码train.py重新预训练了t5,最后保存的模型是keras保存的.weights文件,需要转成ckpt才能用这里的convert.py,请问你预训练的时候遇到过这个问题吗，是怎么解决的呢？

请问下 model.ckpt-1000000怎么在哪下载呢？
