### ISSUE TITLE
请问如何加载生成的summary_model权重文件呢？

### ISSUE THREAD

**Issue by wxtt522** [renmada/t5-pegasus-pytorch#15]

**Comment by renmada** [comment]
from_pretrained
训练怎么加载这个就怎么加载

**Comment by wxtt522** [comment]
> from_pretrained
> 训练怎么加载这个就怎么加载

谢谢，已经知道怎么加载了，但还是有点问题希望能够解惑。我使用convert.py文件转换的追一科技base预训练模型，然后分别用预训练模型和同一批语料进行微调，发现生成的摘要差别还是很明显，不清楚是什么原因造成的。

http://loc.dingtalk.com/f6dbb85f473d8082c18382478e466061877dfc3b5e2bb39209f592fcbc3aa16bQzpcVXNlcnNcYWRtaW5cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDIxMDc3NjYwMV92MlxJbWFnZUZpbGVzXDE2MjkyNzA4NzY4NjJfNkI5OEI4OUYtNERFNi00N2JmLTk4OUYtOTBEOURCQkQ0MDVDLnBuZw==?renderHeight=228&renderOrientation=1&renderWidth=1793


http://loc.dingtalk.com/0bd4a120f880668dcafe66931b9a0ee78607692bc0fc8f93b7bf7085ddda40e0QzpcVXNlcnNcYWRtaW5cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDIxMDc3NjYwMV92MlxJbWFnZUZpbGVzXDE2MjkyNjg2MjI0MDJfRDEwRUE3NDQtRjFDNi00NTM2LUE3RTMtODdERDlEMTEyNjZELnBuZw==?renderHeight=201&renderOrientation=1&renderWidth=1718

**Comment by renmada** [comment]
> > from_pretrained
> > 训练怎么加载这个就怎么加载
> 
> 谢谢，已经知道怎么加载了，但还是有点问题希望能够解惑。我使用convert.py文件转换的追一科技base预训练模型，然后分别用预训练模型和同一批语料进行微调，发现生成的摘要差别还是很明显，不清楚是什么原因造成的。
> 
> ![0bd4a120f880668dcafe66931b9a0ee78607692bc0fc8f93b7bf7085ddda40e0QzpcVXNlcnNcYWRtaW5cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDIxMDc3NjYwMV92MlxJbWFnZUZpbGVzXDE2MjkyNjg2MjI0MDJfRDEwRUE3NDQtRjFDNi00NTM2LUE3RTMtODdERDlEMTEyNjZELnBuZw==](https://user-images.githubusercontent.com/28422636/129854710-f42414c0-28f5-4139-9721-88f8c803176b.png)
> 
> ![f6dbb85f473d8082c18382478e466061877dfc3b5e2bb39209f592fcbc3aa16bQzpcVXNlcnNcYWRtaW5cQXBwRGF0YVxSb2FtaW5nXERpbmdUYWxrXDIxMDc3NjYwMV92MlxJbWFnZUZpbGVzXDE2MjkyNzA4NzY4NjJfNkI5OEI4OUYtNERFNi00N2JmLTk4OUYtOTBEOURCQkQ0MDVDLnBuZw==](https://user-images.githubusercontent.com/28422636/129854720-53fbf184-faca-406a-b9b6-334d20f51020.png)
你用bert4kreas训练两次，结果也不会一样啊
