### ISSUE TITLE
使用预训练模型微调

### ISSUE THREAD

**Issue by JoeyHang** [renmada/t5-pegasus-pytorch#22]
麻烦问下t5-pegasus是否支持使用自己的语料进行微调，是否有相关资料呢～谢谢～

**Comment by tzq0301** [comment]
同问

**Comment by renmada** [comment]
这里
https://github.com/renmada/t5-pegasus-pytorch/tree/main/examples

**Comment by zacharykzhao** [comment]
> 这里 https://github.com/renmada/t5-pegasus-pytorch/tree/main/examples

作者你好，这个这个脚本方便再提供下吗，非常感谢
