### ISSUE TITLE
tokenizer的问题

### ISSUE THREAD

**Issue by MaoPopovich** [renmada/t5-pegasus-pytorch#25]
运行test有以下提示：“The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'T5Tokenizer'. 
The class this function is called from is 'T5PegasusTokenizer'.”
另外，运行结果也很奇怪
<img width="313" alt="image" src="https://user-images.githubusercontent.com/47314106/157156158-f2f55353-130f-49dd-a8f0-359131c1a0a3.png">

**Comment by renmada** [comment]
warning可以忽视

**Comment by D1026** [comment]
> 运行test有以下提示：“The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. The tokenizer class you load from this checkpoint is 'T5Tokenizer'. The class this function is called from is 'T5PegasusTokenizer'.” 另外，运行结果也很奇怪 <img alt="image" width="313" src="https://user-images.githubusercontent.com/47314106/157156158-f2f55353-130f-49dd-a8f0-359131c1a0a3.png">

这个T5PegasusTokenizer 是[utils.py](https://github.com/renmada/t5-pegasus-pytorch/blob/main/examples/utils.py) 重写的那个对吗

**Comment by renmada** [comment]
> 

是的。提示都是warning，可以忽略

**Comment by shuxinyin** [comment]
> 是的。提示都是warning，可以忽略

上面这个预测结果是正常的么？
