### ISSUE TITLE
t5_pegasus keras版本到pytorch版本如何转化？

### ISSUE THREAD

**Issue by chenchenhaha** [renmada/t5-pegasus-pytorch#33]
请问可以分享keras版本到pytorch版本的转换代码吗？自己重新做了T5_pegasus的预训练，想将模型转换成pyrorch版本

**Comment by chenchenhaha** [comment]
已经转换成ckpt了，求助楼主之前cpkt转bin的conver.py

**Comment by renmada** [comment]
https://github.com/renmada/t5-pegasus-pytorch/blob/4d7f1a7d1bdb54b538765781c4374b404e57db8c/convert.py
