### ISSUE TITLE
The difference of released pretrained model

### ISSUE THREAD

**Issue by airsYuan** [renmada/t5-pegasus-pytorch#43]
t5-pegasus-base
t5-copy
t5-copy-summary
你好，请问这几个模型有什么区别呢？第一个应该是和追一开源的类似，以pegasus方式在摘要任务上训练过；t5-copy是怎么训练的呢；t5-copy-summary和前者有何区别，还是和t5-pegasus-base一样只是加了pointer？

期待您的回复

**Comment by renmada** [comment]
- t5-pegasus-base是追一科技开源的
- t5-copy在t5-pegasus的基础上增加了**pointer generator**，用t5-pegasus的预训练任务继续训练
- t5-copy-large模型，在**t5-copy**的基础上用公开的文本摘要数据集进行训练

**Comment by airsYuan** [comment]
> 
感谢回复，因为我用追一和当前版本的t5-pegasus-base在一个类似摘要的生成任务上评测了下，发现追一的按本要好很多，不知道是不是超参数设置的原因。

**Comment by airsYuan** [comment]
> * t5-pegasus-base是追一科技开源的
> * t5-copy在t5-pegasus的基础上增加了**pointer generator**，用t5-pegasus的预训练任务继续训练
> * t5-copy-large模型，在**t5-copy**的基础上用公开的文本摘要数据集进行训练
感谢回复，因为我用追一和当前版本的t5-pegasus-base在一个类似摘要的生成任务上评测了下，发现追一的按本要好很多，不知道是不是超参数设置的原因。

**Comment by renmada** [comment]
https://github.com/renmada/t5-pegasus-pytorch/issues/16
t5-pegasus-base转换的权重存小问题，训练数据量小的话是可能出现这个情况。
另外，生成任务为什么用acc做评估？

**Comment by airsYuan** [comment]
"权重存小问题"指的是？我用的训练数据量是1w。这是个QA问题，答案形式和VQA的答案风格很像，都是名词或短语，一般几个字符，所以选择了ACC。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "renmada/t5-pegasus-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月27日(星期一) 下午2:11
***@***.***&gt;;
抄送:&nbsp;"undergraduate ***@***.******@***.***&gt;;
主题:&nbsp;Re: [renmada/t5-pegasus-pytorch] The difference of released pretrained model (Issue #43)





 
#16
 t5-pegasus-base转换的权重存小问题，训练数据量小的话是可能出现这个情况。
 另外，生成任务为什么用acc做评估？

**Comment by renmada** [comment]
就是模型权重有2个没转过来，具体见https://github.com/renmada/t5-pegasus-pytorch/issues/16
的数据量应该是够
