### ISSUE TITLE
t5_copy inference报错

### ISSUE THREAD

**Issue by airsYuan** [renmada/t5-pegasus-pytorch#44]
File "/.conda/envs/t5-torch/lib/python3.7/site-packages/transformers/generation_utils.py", line 847, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(input_ids, model_kwargs)
File "t5-pegasus-pytorch-main/examples/t5_copy.py", line 48, in _prepare_encoder_decoder_kwargs_for_generation
    new_kwargs.pop('src')
KeyError: 'src

显示_prepare_encoder_decoder_kwargs_for_generation中的字典new_kwargs没有这个键，入参model_kwargs中以及其父类的函数中也没有找到类似的键，请问原因是什么
所有的版本均于推荐一致

**Comment by renmada** [comment]
贴一下你的代码

**Comment by airsYuan** [comment]
> 贴一下你的代码

日志就是上面贴出来的部分，代码位置是文件t5_copy.py第48行，该函数如下：
    def _prepare_encoder_decoder_kwargs_for_generation(self, input_ids, model_kwargs):
        if "encoder_outputs" not in model_kwargs:
            # retrieve encoder hidden states
            encoder = self.get_encoder()
            encoder_kwargs = {
                argument: value
                for argument, value in model_kwargs.items()
                if not (argument.startswith("decoder_") or argument.starth("cross_attn"))
            }
            new_kwargs = copy.deepcopy(encoder_kwargs)
            new_kwargs.pop('src')
            model_kwargs["encoder_outputs"] = encoder(input_ids, return_dict=True, **new_kwargs)
        return model_kwargs

运行时，encoder_kwargs并没与"src"这个键，因此new_kwargs中也不会有，直接注释了下面也会用到这个因此会出错，我猜这个"src"应该对应于这个函数的入参input_ids？是否应该有一个赋值操作呢？

**Comment by renmada** [comment]
是训练还是预测的遇到的，可能是使用方法不对。
试试这个例子
```
    model = T5Copy.from_pretrained(model_path)
    print(model.generate(torch.LongTensor([[0, 1, 2, 3]]), src=torch.LongTensor([[0, 1, 2, 3]])))
```

**Comment by airsYuan** [comment]
> 是训练还是预测的遇到的，可能是使用方法不对。 试试这个例子
> 
> ```
>     model = T5Copy.from_pretrained(model_path)
>     print(model.generate(torch.LongTensor([[0, 1, 2, 3]]), src=torch.LongTensor([[0, 1, 2, 3]])))
> ```

是预测出的问题，请问src这个参数的意义是什么呢？我把t5_copy.py 下的_prepare_encoder_decoder_kwargs_for_generation中增加encoder_kwargs['src'] = input_ids似乎正常了，但是不知道是否对结果有影响。

另外直接运行发来的demo case显示
  File "<stdin>", line 1, in <module>
  File ".conda/envs/t5-torch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File ".conda/envs/t5-torch/lib/python3.7/site-packages/transformers/generation_utils.py", line 913, in generate
    **model_kwargs,
  File ".conda/envs/t5-torch/lib/python3.7/site-packages/transformers/generation_utils.py", line 1177, in greedy_search
    output_hidden_states=output_hidden_states,
  File ".conda/envs/t5-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "t5-pegasus-pytorch-main/examples/t5_copy.py", line 123, in forward
    prob = self.generator(src, decode_output, decode_attn, memory, gen_logits)
  File ".conda/envs/t5-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "t5-pegasus-pytorch-main/examples/t5_copy.py", line 24, in forward
    copy_logits = copy_logits.scatter_add(2, src, decode_attn)
RuntimeError: Expected index [1, 1, 4] to be smaller than self [1, 1, 50000] apart from dimension 2 and to be smaller size than src [1, 1, 3]

**Comment by renmada** [comment]
transformers是4.12.0吗，demo case我刚测过没问题

**Comment by renmada** [comment]
> > 贴一下你的代码
> 
> 日志就是上面贴出来的部分，代码位置是文件t5_copy.py第48行，该函数如下： def _prepare_encoder_decoder_kwargs_for_generation(self, input_ids, model_kwargs): if "encoder_outputs" not in model_kwargs: # retrieve encoder hidden states encoder = self.get_encoder() encoder_kwargs = { argument: value for argument, value in model_kwargs.items() if not (argument.startswith("decoder_") or argument.starth("cross_attn")) } new_kwargs = copy.deepcopy(encoder_kwargs) new_kwargs.pop('src') model_kwargs["encoder_outputs"] = encoder(input_ids, return_dict=True, **new_kwargs) return model_kwargs
> 
> 运行时，encoder_kwargs并没与"src"这个键，因此new_kwargs中也不会有，直接注释了下面也会用到这个因此会出错，我猜这个"src"应该对应于这个函数的入参input_ids？是否应该有一个赋值操作呢？

```python
    def prepare_inputs_for_generation(
            self,
            input_ids,
            past=None,
            attention_mask=None,
            head_mask=None,
            decoder_head_mask=None,
            cross_attn_head_mask=None,
            use_cache=None,
            encoder_outputs=None,
            **kwargs
    ):
        res = super().prepare_inputs_for_generation(input_ids,
                                                    past,
                                                    attention_mask,
                                                    head_mask,
                                                    decoder_head_mask,
                                                    cross_attn_head_mask,
                                                    use_cache,
                                                    encoder_outputs,
                                                    **kwargs)
        res['src'] = kwargs['src']
        return res
```
这里有把src加到kwargs里

**Comment by renmada** [comment]
transformers  4.12.0
src就是input ids，是copy的来源

**Comment by airsYuan** [comment]
> transformers 4.12.0 src就是input ids，是copy的来源

好的感谢，修改完版本这个问题已经解决了。
