### ISSUE TITLE
请问输入长度是否有限制，根据输入格式训练可以完成文本摘要任务吗

### ISSUE THREAD

**Issue by Enderfga** [renmada/t5-pegasus-pytorch#50]
您好，我看示例数据的格式是
{"src": "类型#裤*版型#宽松*风格#性感*图案#线条*裤型#阔腿裤", "tgt": "宽松的阔腿裤这两年真的吸粉不少，明星时尚达人的心头爱。毕竟好穿时尚，谁都能穿出腿长2米的效果宽松的裤腿，当然是遮肉小能手啊。上身随性自然不拘束，面料亲肤舒适贴身体验感棒棒哒。系带部分增加设计看点，还让单品的设计感更强。腿部线条若隐若现的，性感撩人。颜色敲温柔的，与裤子本身所呈现的风格有点反差萌。"}

据此我把数据统一成{"src":"长文本","tgt":"摘要"}
然后使用[examples](https://github.com/renmada/t5-pegasus-pytorch/tree/main/examples)/train_t5_copy.py
是否就可以微调模型，训练出文本摘要的模型呢

还有就是我打算使用https://github.com/lxj5957/CLTS-plus-Dataset 这个数据集
里面的src文本较长（5k） 是否修改输入长度512就好

**Comment by renmada** [comment]
t5用的相对位置编码，模型本身不限制输入长度。但是长度太大，显存可能不够用

**Comment by yapimingye** [comment]
> 您好，我看示例数据的格式是 {"src": "类型#裤_版型#宽松_风格#性感_图案#线条_裤型#阔腿裤", "tgt": "宽松的阔腿裤这两年真的吸粉不少，明星时尚达人的心头爱。毕竟好穿时尚，谁都能穿出腿长2米的效果宽松的裤腿，当然是遮肉小能手啊。上身随性自然不拘束，面料亲肤舒适贴身体验感棒棒哒。系带部分增加设计看点，还让单品的设计感更强。腿部线条若隐若现的，性感撩人。颜色敲温柔的，与裤子本身所呈现的风格有点反差萌。"}
> 
> 据此我把数据统一成{"src":"长文本","tgt":"摘要"} 然后使用[examples](https://github.com/renmada/t5-pegasus-pytorch/tree/main/examples)/train_t5_copy.py 是否就可以微调模型，训练出文本摘要的模型呢
> 
> 还有就是我打算使用https://github.com/lxj5957/CLTS-plus-Dataset 这个数据集 里面的src文本较长（5k） 是否修改输入长度512就好

朋友，我改成长文本之后报错了ValueError: You have to specify either input_ids or inputs_embeds
Epoch 2:  89%|████████▉ | 1905/2142 [22:16<02:46,  1.43it/s, loss=0.487]                                                                                                                                                  
                                                                                                                                                                                                                         free(): invalid pointer                                                                                                                                                                                                    
Aborted (core dumped)，你那边怎么样？

**Comment by renmada** [comment]
好像是数据的问题
