### ISSUE TITLE
T5与T5-Cpoy的指标对比

### ISSUE THREAD

**Issue by shihanmax** [renmada/t5-pegasus-pytorch#55]
作者你好，看到你在[AdvertiseGen](https://www.luge.ai/#/luge/dataDetail?id=9)上对比了T5 pegasus和加入Pointer generator的T5-Copy模型的效果，观察到BLEU和ROUGE*基本上原版T5 pegasus的结果都稍微优于T5-Copy的；
考虑到T5-Copy是在T5 的基础上加入了复制机制后，重新使用pegasus提出的预训练方法继续预训练的，加入Copy预期是能够提升生成效果的，但实验指标上却有所降低（包括我自己在自有数据集上做的，也观察到了类似的现象），所以有几个问题想和作者还有路过的各位大佬讨论一下：

1. T5-Copy在T5 pegasus的基础上，采用的是原版[Pegasus论文](https://arxiv.org/abs/1912.08777)中的预训练方式还是采用[苏建林老师博客](https://kexue.fm/archives/8209)提到的方法呢
2. 继续预训练所采用的数据规模、质量等方便透露一下么
3. 加入Copy后指标降低的原因可能是引入Copy本身造成的，也有可能是继续预训练效果不达预期造成的，不知道这方面作者有没有做过相关的对比

期待解答！最后还是感谢作者的无私开源～

**Comment by renmada** [comment]
1. 苏老师的方法
2. [WuDaoCorpora](https://data.wudaoai.cn/home?ind&name=WuDaoCorpora%202.0&id=1394901288847716352)
3. 理论上继续预训练比苏老师的T5 pegasus用的数据要多。你可以试试用T5 pegasus的权重去初始化T5-Copy在你的数据集上试试，如果仍然比T5 pegasus效果还差的话，应该是copy的问题

**Comment by shihanmax** [comment]
好的，谢谢！
