### ISSUE TITLE
T5的samll版本是怎么得到的？

### ISSUE THREAD

**Issue by demeiyan** [renmada/t5-pegasus-pytorch#8]
你那个百度云盘中T5的small版本是通过原来tensorflow的模型参数转换过来的吗？

**Comment by renmada** [comment]
是的

**Comment by demeiyan** [comment]
是苏神的预训练模型吧？[https://github.com/ZhuiyiTechnology/t5-pegasus](url)

**Comment by liyucheng09** [comment]
@renmada 老兄，small版本的模型无法正常运行。generate方法只会原样返回输入的文本。老兄知道是哪方面的问题吗？

**Comment by renmada** [comment]
> @renmada 老兄，small版本的模型无法正常运行。generate方法只会原样返回输入的文本。老兄知道是哪方面的问题吗？

生产项目上用过small模型，没遇到这个问题
